export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR = 'AUTH_CLEAR';
export const COMICS_FETCH = 'COMICS_FETCH';
export const COMICS_CLEAR = 'COMICS_CLEAR';
export const CREATORS_FETCH = 'CREATORS_FETCH';
export const CREATORS_CLEAR = 'CREATORS_CLEAR';
export const FAVORITE_CREATE = 'FAVORITE_CREATE';
export const FAVORITE_ADD = 'FAVORITE_ADD';
export const FAVORITE_CLEAR = 'FAVORITE_CLEAR';

